# Generated by Django 4.2.7 on 2023-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
